### ISSUE TITLE
3/7 THU ~ 3/13 WED Sprint - ongheong

### ISSUE THREAD

**Issue by ongheong** [FF-UNI-SPHERE/UNISPHERE-WEB#22]
- [ ] 기술 아카이브에 정리 : JS객체의 정의와 응용, html 캔버스로 아바타 이미지 로드, 아바타 이미지를 S3 버킷에 업로드한 과정
- [ ] 마이페이지 :  탭 - 나의 정보 확인 ( 이름, 자기소개, 내가 속한 단체 보기 리스트) 뷰 만들기
- [ ] 마이페이지 : 내가 속한 단체 목록 보기 기능의 경우 해당 단체 페이지로 이동 기능 + 단체 탈퇴 기능 넣기
- [ ] 마이페이지 : 탭 - 아바타 편집 ( 기존 아바타 기능 여기에 넣기, 좌우버튼으로 이미지 변경) 뷰 만들기
- [x] 마이페이지 : 아바타가 없을 경우 블러 처리 or 회색 아바타 이미지 넣기
- [ ] 페이지 디자인 : 지수언니랑 남은 페이지(모든단체보기, 단체관리, 유니스피어 관리) 분담해서 Figma로 디자인하기

**Comment by StopSoo** [comment]
- 모든 단체 보기, 단체 관리, 유니스피어 관리 페이지도 목데이터로 해야 하나 ...?
- 회색 아바타 옹심이가 만들 건가용?
- 아바타 편집 탭 이번 주 회의 때 보여줬던 화살표 넘기는 페이지 맞죵 그것도 피그마에 같이 만들면 좋을 것 같아용
- 단체 탈퇴 ........................ 해야 하겠죠? ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ ㅠ
- JS 공부 ... 다시 ... 나도 ...

**Comment by ongheong** [comment]
- 일단 디자인만 할거라 구현부분은 생각 안해봤는데 아마 그렇게 해야할 것 같네용
- 넵 회색아바타 제가 합니다
- 아바타 편집 탭 지금 피그마에 있어요! 보시고 수정할거 있으면 피그마에 코멘트 남겨주셔요
- 그...렇죠...>?ㅋㅋ쿠ㅜ메인화면에서 단체아바타 수정될텐데....요건 어떻게 구현할지 다음 회의시간에 한번 얘기해보면 좋을 것 같아요

**Comment by StopSoo** [comment]
> * 일단 디자인만 할거라 구현부분은 생각 안해봤는데 아마 그렇게 해야할 것 같네용
> * 넵 회색아바타 제가 합니다
> * 아바타 편집 탭 지금 피그마에 있어요! 보시고 수정할거 있으면 피그마에 코멘트 남겨주셔요
> * 그...렇죠...>?ㅋㅋ쿠ㅜ메인화면에서 단체아바타 수정될텐데....요건 어떻게 구현할지 다음 회의시간에 한번 얘기해보면 좋을 것 같아요

아 오케이 아이가릿
